# Generated by Django 3.1 on 2020-08-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombres',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
